# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c9b98c5222e41b1fece2db3fec6aea8"
application_url = "https://example.com"
embedded = true
name = "Deliverly"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_app_proxy,read_themes"

[app_proxy]
url = "/api/estimate"
prefix = "apps"
subpath = "delivery-estimate"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
